/**
 * Turn compliance findings into an actionable, Claude-ready **fix plan** — a
 * Markdown brief the developer reviews and then hands to Claude Code, which
 * applies the changes via the Fuuz MCP mutation tools. The extension never
 * mutates the tenant itself: it proposes (heuristic seeds), the human accepts,
 * Claude executes. Pure string-building, no VS Code/Node imports.
 */
import { ComplianceReport, Finding } from './complianceTypes';
import { FlowGraph } from './flowTypes';

export interface FlowFixInput { graph: FlowGraph; report: ComplianceReport; }

const PREAMBLE = (subject: string) => [
  `# Fuuz fix plan — ${subject}`,
  '',
  '> Generated by the Fuuz VS Code extension. **Review and edit before running.**',
  '> Then run this with Claude Code; it will apply the changes using the Fuuz MCP.',
  '',
  '## How to apply (Claude)',
  '',
  '- Use **only the platform `system_*` MCP tools**. Do not use `data_flow_*` tools (they are user-built and unreliable).',
  '- Read current state with `system_query_model` (`DataFlowElement`, `Screen`/`ScreenElement`, `DataModel`, `SavedTransform`, `SavedQuery`).',
  '- Apply changes with `system_data_flow_mutations` (flow nodes), `system_saved_transform_mutations` (Saved Scripts), and the platform’s saved-query mutation (introspect the available `system_*` mutation tools to confirm its exact name/shape).',
  '- After each flow’s edits, create a new version and deploy with `system_deploy_app_component_version`.',
  '- **Confirm each change set with me before mutating.** Make the smallest change that satisfies the item; do not touch unrelated nodes.',
  '- Suggested names below are heuristic seeds — **refine them** against the node’s real role before applying.',
  '',
].join('\n');

const byRule = (r: ComplianceReport, id: string): Finding[] => r.findings.filter(f => f.ruleId === id);
const CAP = 50;
const capNote = (n: number) => (n > CAP ? `\n\n_(+${n - CAP} more — re-run after this pass.)_` : '');

/** Render the per-flow remediation sections (returns '' when nothing to do). */
function flowSections(graph: FlowGraph, report: ComplianceReport): string {
  const out: string[] = [];

  const renames = byRule(report, 'flow-node-naming');
  if (renames.length) {
    const rows = renames.slice(0, CAP).map(f => `| \`${f.targetId ?? ''}\` | ${f.where ?? ''} | ${f.suggestion ?? ''} |`).join('\n');
    out.push([
      `### Rename nodes (${renames.length})`,
      'Refine each suggested name to describe what the node does, then apply via `system_data_flow_mutations` (update the element `name`).',
      '',
      '| node id | current | suggested (refine) |',
      '| --- | --- | --- |',
      rows + capNote(renames.length),
    ].join('\n'));
  }

  const descs = byRule(report, 'flow-node-descriptions');
  if (descs.length) {
    out.push([
      `### Add node descriptions (${descs.length})`,
      'Write a one-line description for each node (what it does + why), then apply via `system_data_flow_mutations`.',
      '',
      descs.slice(0, CAP).map(f => `- \`${f.targetId ?? ''}\` — ${f.where ?? ''}`).join('\n') + capNote(descs.length),
    ].join('\n'));
  }

  const longScripts = byRule(report, 'flow-long-scripts');
  if (longScripts.length) {
    out.push([
      `### Extract long inline scripts → Saved Scripts (${longScripts.length})`,
      'For each: create a Saved Script (`system_saved_transform_mutations`) with the node’s JavaScript and a declared **input schema** (the shape it reads from context); then replace the inline `javascriptTransform` node with a `savedTransformV2` node referencing it, mapping inputs via `requestTransform`. Verify behavior, then deploy.',
      '',
      longScripts.slice(0, CAP).map(f => `- \`${f.targetId ?? ''}\` — ${f.where ?? ''} → Saved Script “${f.suggestion ?? ''}”`).join('\n') + capNote(longScripts.length),
    ].join('\n'));
  }

  const contracts = byRule(report, 'flow-saved-contract');
  if (contracts.length) {
    out.push([
      `### Add payload contracts to saved scripts/queries (${contracts.length})`,
      'Each of these passes the entire context (`$`) into a saved transform. Add a **Validate** node before it (or a `requestTransform` that maps to the saved transform’s `inputSchema`) so a bad payload fails fast with a clear error.',
      '',
      contracts.slice(0, CAP).map(f => `- \`${f.targetId ?? ''}\` — ${f.where ?? ''}`).join('\n') + capNote(contracts.length),
    ].join('\n'));
  }

  const scoping = byRule(report, 'flow-query-scoping');
  if (scoping.length) {
    out.push([
      `### Scope or paginate unfiltered queries (${scoping.length})`,
      'Add a `where:` filter scoped to the request, or implement a pagination cycle (store each page in context, track `nextPage`/cursor, loop until exhausted). Setup-type models are exempt.',
      '',
      scoping.slice(0, CAP).map(f => `- \`${f.targetId ?? ''}\` — ${f.message}`).join('\n') + capNote(scoping.length),
    ].join('\n'));
  }

  const pageSize = byRule(report, 'flow-query-pagesize');
  if (pageSize.length) {
    out.push([
      `### Reduce oversized queries (${pageSize.length})`,
      'Lower the page size and/or paginate; avoid deep nested `edges` in a single pull.',
      '',
      pageSize.slice(0, CAP).map(f => `- \`${f.targetId ?? ''}\` — ${f.message}`).join('\n') + capNote(pageSize.length),
    ].join('\n'));
  }

  const integrate = byRule(report, 'flow-integrate-in-script');
  const creds = byRule(report, 'flow-credentials');
  const errors = byRule(report, 'flow-error-handling');
  if (integrate.length || creds.length || errors.length) {
    const lines: string[] = [];
    for (const f of creds) lines.push(`- 🔴 **Credential risk** \`${f.targetId ?? ''}\` — ${f.where ?? ''}: move the secret to a Connection.`);
    for (const f of integrate) lines.push(`- 🔴 \`${f.targetId ?? ''}\` — ${f.where ?? ''}: replace in-script \`$integrate\` with an HTTP node + Connection.`);
    for (const f of errors) lines.push(`- ⚠️ ${f.message}: add a Try/Catch node and an error response.`);
    out.push(`### Reliability & security\n\n${lines.join('\n')}`);
  }

  const vNotes = byRule(report, 'flow-version-notes');
  const fNaming = byRule(report, 'flow-naming');
  if (vNotes.length || fNaming.length) {
    const lines: string[] = [];
    for (const f of fNaming) lines.push(`- Rename the flow: ${f.message}`);
    for (const f of vNotes) lines.push(`- ${f.message} — add a description to each deployed version describing what changed.`);
    out.push(`### Naming & release notes\n\n${lines.join('\n')}`);
  }

  if (out.length === 0) return '';
  return [`## ${graph.name}  \nFlow id: \`${graph.id}\` · score ${report.score}%`, '', out.join('\n\n')].join('\n');
}

/** A fix plan for one flow. */
export function buildFlowFixPlan(graph: FlowGraph, report: ComplianceReport): string {
  const body = flowSections(graph, report);
  return [PREAMBLE(graph.name), body || '_No actionable findings — this flow is compliant._', ''].join('\n');
}

export interface TenantFixInput {
  flows: FlowFixInput[];
  /** Cross-flow report (shared scripts/queries). */
  cross?: ComplianceReport;
  screens?: ComplianceReport[];
}

/** Cross-flow extraction section (shared/similar scripts & queries). */
function crossSection(cross: ComplianceReport | undefined): string {
  if (!cross) return '';
  const q = cross.findings.filter(f => f.ruleId === 'flow-shared-query');
  const s = cross.findings.filter(f => f.ruleId === 'flow-shared-script');
  if (!q.length && !s.length) return '';
  const lines: string[] = ['## Shared logic across flows', ''];
  if (s.length) {
    lines.push('### Extract similar scripts → Saved Scripts', 'For each cluster, create one Saved Script, parameterize the differences via `requestTransform`, and point every listed flow’s node at it (`savedTransformV2`).', '');
    lines.push(...s.map(f => `- ${f.message}\n  → Saved Script “${f.suggestion ?? ''}”`));
    lines.push('');
  }
  if (q.length) {
    lines.push('### Extract similar queries → Saved Queries', 'For each cluster, create one Saved Query, parameterize the differences, and reference it from every listed flow.', '');
    lines.push(...q.map(f => `- ${f.message}\n  → Saved Query “${f.suggestion ?? ''}”`));
  }
  return lines.join('\n');
}

/** Screen remediation summary (kept compact — details via per-screen reports). */
function screenSection(screens: ComplianceReport[] | undefined): string {
  if (!screens?.length) return '';
  const flagged = screens.filter(s => s.findings.length).sort((a, b) => a.score - b.score).slice(0, 20);
  if (!flagged.length) return '';
  const lines = ['## Screens to groom', ''];
  for (const s of flagged) {
    lines.push(`- **${s.name}** (${s.score}%): ${s.findings.slice(0, 4).map(f => f.message).join('; ')}`);
  }
  lines.push('', 'Move inline column transforms to a single **Table** transform and inline form-field transforms to a **Form** transform; split screens with > 75 elements or > 5 action buttons.');
  return lines.join('\n');
}

/** A whole-tenant fix plan: worst flows first, then cross-flow extraction + screens. */
export function buildTenantFixPlan(tenantName: string, input: TenantFixInput): string {
  const flows = input.flows
    .filter(f => f.report.findings.length)
    .sort((a, b) => a.report.score - b.report.score);

  const parts = [PREAMBLE(`tenant ${tenantName}`)];
  const cross = crossSection(input.cross);
  if (cross) parts.push(cross);

  if (flows.length) {
    parts.push(`## Per-flow fixes (${flows.length} flows, worst first)`);
    for (const f of flows.slice(0, 40)) {
      const body = flowSections(f.graph, f.report);
      if (body) parts.push(body);
    }
    if (flows.length > 40) parts.push(`_(+${flows.length - 40} more flows — re-run after this pass.)_`);
  }

  const screens = screenSection(input.screens);
  if (screens) parts.push(screens);

  if (!cross && !flows.length && !screens) parts.push('_No actionable findings — tenant is compliant._');
  return parts.join('\n\n') + '\n';
}
