/**
 * Render a {@link ComplianceReport} as Markdown for an editor tab. (A richer
 * webview report is the planned next step; Markdown keeps the first slice
 * self-contained and diff-friendly.)
 */
import { ComplianceReport, Finding } from './complianceTypes';

const ICON = { error: '🔴', warn: '🟡', info: '🔵' } as const;

function badge(score: number): string {
  if (score >= 100) return '✅ 100% — fully compliant';
  if (score >= 90) return `🟢 ${score}% — compliant with minor notes`;
  if (score >= 80) return `🟡 ${score}% — mostly compliant`;
  return `🔴 ${score}% — needs work`;
}

export function reportToMarkdown(r: ComplianceReport): string {
  const lines: string[] = [];
  lines.push(`# Compliance — ${r.name}  \n`);
  lines.push(`**${badge(r.score)}**  ·  ${r.passed}/${r.checks} checks passed  ·  kind: \`${r.kind}\`\n`);

  const bySev = (s: Finding['severity']) => r.findings.filter(f => f.severity === s);
  const errs = bySev('error'), warns = bySev('warn'), infos = bySev('info');
  lines.push(`> ${ICON.error} ${errs.length} errors · ${ICON.warn} ${warns.length} warnings · ${ICON.info} ${infos.length} info\n`);

  if (r.findings.length) {
    lines.push(`## Findings\n`);
    for (const f of r.findings) {
      const where = f.where ? ` \`${f.where}\`` : '';
      lines.push(`- ${ICON[f.severity]} **${f.message}**${where}`);
      if (f.fix) lines.push(`  - _Fix:_ ${f.fix}`);
    }
    lines.push('');
  } else {
    lines.push(`No findings — every check passed. 🎉\n`);
  }

  lines.push(`## Rules\n`);
  lines.push(`| Rule | Checks | Passed |`);
  lines.push(`| --- | ---: | ---: |`);
  for (const rule of r.rules) {
    const mark = rule.passed === rule.checks ? '' : ' ⚠️';
    lines.push(`| ${rule.title}${mark} | ${rule.checks} | ${rule.passed} |`);
  }
  lines.push('');
  lines.push(`_Generated by Fuuz Schema Doctor — a local check of platform conventions before you push to Fuuz._`);
  return lines.join('\n');
}
